export const PERMISSIONS = Object.freeze({
  ORGANIZATION_READ: 'organization.read',
  ORGANIZATION_UPDATE: 'organization.update',
  ORGANIZATION_CLOSE: 'organization.close',
  ORGANIZATION_TRANSFER_OWNERSHIP: 'organization.transfer_ownership',
  MEMBERSHIP_READ: 'membership.read',
  MEMBERSHIP_INVITE: 'membership.invite',
  MEMBERSHIP_CHANGE_ROLE: 'membership.change_role',
  MEMBERSHIP_SUSPEND: 'membership.suspend',
  MEMBERSHIP_REMOVE: 'membership.remove',
  CUSTOMER_READ: 'customer.read',
  CUSTOMER_CREATE: 'customer.create',
  CUSTOMER_UPDATE: 'customer.update',
  CUSTOMER_ARCHIVE: 'customer.archive',
  INVOICE_READ: 'invoice.read',
  INVOICE_CREATE: 'invoice.create',
  INVOICE_UPDATE_DRAFT: 'invoice.update_draft',
  INVOICE_DELETE_DRAFT: 'invoice.delete_draft',
  INVOICE_ISSUE: 'invoice.issue',
  INVOICE_CANCEL: 'invoice.cancel',
  INVOICE_VOID: 'invoice.void',
  PAYMENT_READ: 'payment.read',
  PAYMENT_CREATE: 'payment.create',
  PAYMENT_REVERSE: 'payment.reverse',
  EXPENSE_READ: 'expense.read',
  EXPENSE_CREATE: 'expense.create',
  EXPENSE_UPDATE: 'expense.update',
  EXPENSE_VOID: 'expense.void',
  EXPENSE_CATEGORY_MANAGE: 'expense_category.manage',
  ANALYTICS_READ: 'analytics.read',
  REPORT_READ: 'report.read',
  REPORT_EXPORT: 'report.export',
  NOTIFICATION_READ: 'notification.read',
  NOTIFICATION_UPDATE_SELF: 'notification.update_self',
  AUDIT_READ: 'audit.read',
});

export const ALL_PERMISSIONS = Object.freeze(Object.values(PERMISSIONS));
